/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.Miner.Writer;

import Business.EcoSystem;
import Business.Enterprise.MinerEnterprise;
import Business.Organization.Miner.WritingOrganization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.BitcoinMiningToWritingWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Lei
 */
public class WriterWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form WriterWorkAreaJPanel
     */
    JPanel userProcessContainer;
    UserAccount account;
    WritingOrganization writingOrganization;
    MinerEnterprise minerEnterprise;
    EcoSystem ecoSystem;

    public WriterWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, WritingOrganization writingOrganization, MinerEnterprise minerEnterprise, EcoSystem ecoSystem) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.account = account;
        this.writingOrganization = writingOrganization;
        this.minerEnterprise = minerEnterprise;
        this.ecoSystem = ecoSystem;
        lblEnterpriseName.setText(minerEnterprise.getName());
        populateTable();
    }

    public void populateTable(){
        
        DefaultTableModel model = (DefaultTableModel) tblReques.getModel();
        model.setRowCount(0);
        for(WorkRequest wr : writingOrganization.getWorkQueue().getWorkRequestList()){
            Object[] row = new Object[6];
            row[0] = wr;
            row[1] = wr.getSender().getPerson().getName();
            row[2] = wr.getReceiver() == null ? null : wr.getReceiver().getPerson().getName();
            row[3] = wr.getStatusString();
            
            SimpleDateFormat formatter = new SimpleDateFormat("yyyy-MM-dd");
            String dateString = formatter.format(wr.getRequestDate());
            row[4] = dateString;
            
            if(wr.getResolveDate() == null){
                row[5] = "";
            } else {
                String date = formatter.format(wr.getResolveDate());
                row[5] = date;
            }
            
            model.addRow(row);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlabel = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblEnterpriseName = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblReques = new javax.swing.JTable();
        btnCheck = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jlabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlabel.setText("Enterprise: ");

        jLabel4.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel4.setText("Bitcoin Writer WorkArea");

        lblEnterpriseName.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblEnterpriseName.setText("<Enterprise Name>");

        tblReques.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Message", "Sender", "Reciever", "Status", "Request Date", "Resolve Date"
            }
        ));
        jScrollPane1.setViewportView(tblReques);

        btnCheck.setText("Check >>");
        btnCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 341, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jlabel)
                                .addGap(44, 44, 44)
                                .addComponent(lblEnterpriseName, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(240, 240, 240))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(358, 358, 358))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnCheck))
                            .addComponent(jScrollPane1))
                        .addGap(20, 20, 20))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel4)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEnterpriseName)
                    .addComponent(jlabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(btnCheck)
                .addContainerGap(198, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckActionPerformed
        // TODO add your handling code here:
        int row = tblReques.getSelectedRow();
        if(row < 0){
            JOptionPane.showMessageDialog(null, "Please select a row from the table first.", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        BitcoinMiningToWritingWorkRequest bmtwwr = (BitcoinMiningToWritingWorkRequest) tblReques.getValueAt(row, 0);
        ProcessBitcoinJPanel pbjp = new ProcessBitcoinJPanel(userProcessContainer, account, bmtwwr, ecoSystem);
        userProcessContainer.add("pbjp", pbjp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnCheckActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCheck;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jlabel;
    private javax.swing.JLabel lblEnterpriseName;
    private javax.swing.JTable tblReques;
    // End of variables declaration//GEN-END:variables
}
