/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.Platform.Accountant;

import Business.Employee.Person;
import Business.Other.ExchangeHistory;
import java.awt.CardLayout;
import java.text.DecimalFormat;
import java.util.ArrayList;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author KW
 */
public class ViewExchangeIncomeJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewExchangeIncomeJPanel
     */
    
    JPanel userProcessContainer;
    Person employee;
    ArrayList<ExchangeHistory> buyExchangeHistorys;
    ArrayList<ExchangeHistory> sellExchangeHistorys;
    
    ViewExchangeIncomeJPanel(JPanel userProcessContainer, Person employee, ArrayList<ExchangeHistory> buyExchangeHistory, ArrayList<ExchangeHistory> sellExchangeHistory) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.employee = employee;
        this.buyExchangeHistorys = buyExchangeHistory;
        this.sellExchangeHistorys = sellExchangeHistory;
        lblBrokerName.setText(employee.getName());
        populateTable();
    }
    
    void populateTable(){
        DefaultTableModel model = (DefaultTableModel) tblBrokerIncomeDetail.getModel();
        model.setRowCount(0);
        
        DecimalFormat df = new DecimalFormat("0.00");
        
        for(ExchangeHistory eh : buyExchangeHistorys){
            Object[] row = new Object[4];
            row[0] = eh.getBuyer().getName();
            row[1] = eh.getExchangePrize();
            row[2] = eh.getDate();
            row[3] = df.format(eh.getExchangePrize()*0.02);
            model.addRow(row);
        }
        
        for(ExchangeHistory eh : sellExchangeHistorys){
            Object[] row = new Object[4];
            row[0] = eh.getSeller().getName();
            row[1] = eh.getExchangePrize();
            row[2] = eh.getDate();
            row[3] = df.format(eh.getExchangePrize()*0.02);
            model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBrokerIncomeDetail = new javax.swing.JTable();
        btnBack = new javax.swing.JButton();
        lblBrokerName = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setText("Broker Income Detail");

        tblBrokerIncomeDetail.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Customer", "Deal Price", "Date", "Income"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblBrokerIncomeDetail);
        if (tblBrokerIncomeDetail.getColumnModel().getColumnCount() > 0) {
            tblBrokerIncomeDetail.getColumnModel().getColumn(0).setResizable(false);
            tblBrokerIncomeDetail.getColumnModel().getColumn(1).setResizable(false);
            tblBrokerIncomeDetail.getColumnModel().getColumn(2).setResizable(false);
            tblBrokerIncomeDetail.getColumnModel().getColumn(3).setResizable(false);
        }

        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        lblBrokerName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblBrokerName.setText("jLabel2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(btnBack)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 162, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(208, 208, 208))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 680, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBrokerName, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(158, 158, 158))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(35, 35, 35)
                .addComponent(lblBrokerName)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 218, Short.MAX_VALUE)
                .addComponent(btnBack)
                .addGap(37, 37, 37))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBrokerName;
    private javax.swing.JTable tblBrokerIncomeDetail;
    // End of variables declaration//GEN-END:variables
}
