/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.Depository.Custodian;

import Business.Enterprise.DepositoryEnterprise;
import Business.Organization.Depository.AuthenticationOrganization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.WorkQueue;
import Business.WorkQueue.WorkRequest;
import Business.WorkQueue.WritingToCustodianWorkRequest;
import java.awt.CardLayout;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Lei
 */
public class CustodianVerificationRequestJPanel extends javax.swing.JPanel {

    /**
     * Creates new form WriterWorkAreaJPanel
     */
    JPanel userProcessContainer;
    UserAccount account;
    AuthenticationOrganization authenticationOrganization;
    DepositoryEnterprise depositoryEnterprise;
    WorkQueue workQueue;

    CustodianVerificationRequestJPanel(JPanel userProcessContainer, UserAccount account, DepositoryEnterprise depositoryEnterprise, AuthenticationOrganization authenticationOrganization) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.account = account;
        this.authenticationOrganization = authenticationOrganization;
        this.depositoryEnterprise = depositoryEnterprise;
        workQueue = new WorkQueue();
        for (WorkRequest wr : this.authenticationOrganization.getWorkQueue().getWorkRequestList()) {
            if (wr.getMessage().equals("Report Mined Bitcoin")) {
                workQueue.getWorkRequestList().add(wr);
            }
        }
        populateTable();
        System.out.println(authenticationOrganization.getWorkQueue().getWorkRequestList().size());
    }

    public void populateTable() {
        DefaultTableModel model = (DefaultTableModel) tblReques.getModel();
        model.setRowCount(0);
        for (WorkRequest wr : workQueue.getWorkRequestList()) {
            if(wr instanceof WritingToCustodianWorkRequest){
            Object[] row = new Object[6];
            row[0] = wr;
            row[1] = wr.getSender().getPerson().getName();
            row[2] = wr.getReceiver() == null ? null : wr.getReceiver().getPerson().getName();
            row[3] = wr.getStatusString();

            SimpleDateFormat formatter = new SimpleDateFormat("yyyy-MM-dd");
            String dateString = formatter.format(wr.getRequestDate());
            row[4] = dateString;

            if (wr.getResolveDate() == null) {
                row[5] = "";
            } else {
                String date = formatter.format(wr.getResolveDate());
                row[5] = date;
            }
            model.addRow(row);
        }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblReques = new javax.swing.JTable();
        btnCheck = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel4.setText("Bitcoin Miner WorkArea");

        tblReques.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Message", "Sender", "Reciever", "Status", "Request Date", "Resolve Date"
            }
        ));
        jScrollPane1.setViewportView(tblReques);

        btnCheck.setText("Check >>");
        btnCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckActionPerformed(evt);
            }
        });

        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(357, 357, 357))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnCheck)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 890, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(btnBack)))
                .addGap(32, 57, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel4)
                .addGap(73, 73, 73)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(btnCheck)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 141, Short.MAX_VALUE)
                .addComponent(btnBack)
                .addGap(34, 34, 34))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckActionPerformed
        // TODO add your handling code here:
        int row = tblReques.getSelectedRow();
        if(row < 0){
            JOptionPane.showMessageDialog(null, "Please select a row from the table first.", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        WritingToCustodianWorkRequest wtcwr = (WritingToCustodianWorkRequest) tblReques.getValueAt(row, 0);
        CustodianProcessBitcoinJPanel cpbjp = new CustodianProcessBitcoinJPanel(userProcessContainer, account, depositoryEnterprise, wtcwr);
        userProcessContainer.add("cpbjp", cpbjp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnCheckActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCheck;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblReques;
    // End of variables declaration//GEN-END:variables
}
